version: '3.3'
services:
  mysql:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment: # !!请务必和./src/riot-backend/riot_config.prod.toml保持一致
      MYSQL_DATABASE: riot
      MYSQL_USER: riot
      MYSQL_PASSWORD: RuSsStT.!IiooTt114514
      MYSQL_ROOT_PASSWORD: r3k;4nmed2.4[bnu1el3/031
    ports:
      - '9906:3306'
    expose:
      - '3306'
    volumes:
      - riot_db:/var/lib/mysql
  rumqttd:
    image: bytebeamio/rumqttd
    restart: always
    ports:
      - '1883:1883'
    expose:
      - '1883'
  web:
    build:
      context: .
    restart: always
    environment:
      RUST_LOG: 'debug'
    ports:
      - "7107:8888"
    expose:
      - '7107'
    depends_on:
      - mysql
      - rumqttd
    
volumes:
  riot_db: