SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `record`;
DROP TABLE IF EXISTS `owns`;
DROP TABLE IF EXISTS `tag`;
DROP TABLE IF EXISTS `device`;
DROP TABLE IF EXISTS `user`;
SET FOREIGN_KEY_CHECKS = 1;
