CREATE DATABASE IF NOT EXISTS `riot`;
USE `riot`;
CREATE TABLE IF NOT EXISTS `user` (
    `id` SERIAL PRIMARY KEY,
    `username` VARCHAR(64) NOT NULL UNIQUE,
    `email` VARCHAR(256) NOT NULL UNIQUE,
    `password` VARCHAR(256) NOT NULL,
    `privilege` INT UNSIGNED DEFAULT 0 NOT NULL,
    `api_key` VARCHAR(64) DEFAULT NULL,
    `since` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `activated` BOOLEAN DEFAULT FALSE NOT NULL, -- User is not activated until checking
    INDEX username_index (`username`),
    INDEX email_index (`email`),
    INDEX api_index (`api_key`)
);
CREATE TABLE IF NOT EXISTS `device` (
    `id` SERIAL PRIMARY KEY,
    `uid` BIGINT UNSIGNED NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `desc` TEXT DEFAULT NULL,
    `dtype` INT UNSIGNED DEFAULT 0 NOT NULL,
    `latitude` DOUBLE,
    `longitude` DOUBLE,
    `since` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `last_update` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `activated` BOOLEAN DEFAULT TRUE NOT NULL,
    `topic` VARCHAR(512) NOT NULL UNIQUE,
    INDEX topic_index (`topic`),
    FOREIGN KEY (`uid`) REFERENCES `user`(id) ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS `tag` (
    `id` SERIAL PRIMARY KEY,
    `uid` BIGINT UNSIGNED NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `desc` TEXT,
    `activated` BOOLEAN DEFAULT TRUE NOT NULL,
    FOREIGN KEY (`uid`) REFERENCES `user`(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS `record` (
    `id` SERIAL PRIMARY KEY,
    `did` BIGINT UNSIGNED NOT NULL,
    `payload` BLOB NOT NULL,
    `timestamp` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    FOREIGN KEY (`did`) REFERENCES `device`(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS `owns` (
    `tid` BIGINT UNSIGNED NOT NULL,
    `did` BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (`tid`, `did`),
    FOREIGN KEY (`tid`) REFERENCES `tag`(id) ON DELETE RESTRICT,
    FOREIGN KEY (`did`) REFERENCES `device`(id) ON DELETE RESTRICT
);
