#example config file
[riot]
host = "http://127.0.0.1:8888"
password_salt = "argon2_hash_salt"
[email]
addr = "YourRiot@email.com"
smtp_relay_server = "smtp.email.com"
smtp_username = "riotriot@email.com" # SMTP username
smtp_password = "abcdefghijklmnop" # SMTP password/code
[jwt]
maxage = 86400 # seconds to expire
secret = "jwt_enc_secret"
[mysql]
username = "root"
password = "root"
host = "127.0.0.1"
port = 3306
database = "riot"